version: '3.9'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    environment:
      DB_HOST: host.docker.internal   # or your host IP (e.g., 192.168.2.6)
      DB_PORT: 5432
      DB_NAME: assetdb
      DB_USER: assetuser
      DB_PASSWORD: assetpass
    depends_on:
      - frontend

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: http://localhost:8000
